-- 2026-10-02 공개 데이터 35개 대회 기준. 기존 영어 번역은 덮어쓰지 않습니다.
BEGIN;
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Sangju Gran Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Sangju') WHERE slug = 'sangju';
UPDATE public.events SET comment_en = 'Registration opens on April 8 (Wednesday).' WHERE slug = 'sangju' AND comment = '접수: 4.8(수)' AND NULLIF(BTRIM(comment_en), '') IS NULL;
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Yeongsangang Gran Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Yeongsangang') WHERE slug = 'yeongsan';
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Seorak Gran Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Seorak') WHERE slug = 'seorak';
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Hwacheon DMZ Rally'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Hwacheon') WHERE slug = 'hwacheon';
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Yeoncheon DMZ Rally'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Yeoncheon') WHERE slug = 'yeonchun';
UPDATE public.events SET comment_en = 'The 2026 event has reportedly been cancelled due to circumstances in Yeoncheon County.' WHERE slug = 'yeonchun' AND comment = '2026년 대회는 연천군의 사정으로 인해 취소되었습니다고 합니다 ' AND NULLIF(BTRIM(comment_en), '') IS NULL;
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Yangyang Gran Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Yangyang') WHERE slug = 'yangyang';
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Jeongeup Naejangsan Gran Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Jeongeup') WHERE slug = 'jeongeup';
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Mungyeong Saejae Gran Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Mungyeong Saejae') WHERE slug = 'mungyeong';
UPDATE public.events SET comment_en = 'The 2026 results are scheduled to be updated at 15:00, 18:00 and 22:00 KST.' WHERE slug = 'mungyeong' AND comment = '26년 기록은 15시, 18시, 22시에 기록을 업데이트할 예정입니다' AND NULLIF(BTRIM(comment_en), '') IS NULL;
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Yecheon Jeosuryeong Gran Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Yecheon') WHERE slug = 'jeosu';
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Jeongseon Gran Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Jeongseon') WHERE slug = 'jeongseon';
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Tour de DMZ Goseong Gran Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Goseong') WHERE slug = 'goseong';
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Yangpyeong Gran Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Yangpyeong') WHERE slug = 'yangpyeong';
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Gongju Baekje Gran Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Gongju') WHERE slug = 'gongju';
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Wanju Mangyeonggang Medio Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Wanju Mangyeonggang') WHERE slug = 'wanju';
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Chungju Gran Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Chungju') WHERE slug = 'chungju';
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Around Taebaek Gran Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Taebaek') WHERE slug = 'taebaek';
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Hongcheon Gran Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Hongcheon') WHERE slug = 'hongcheon';
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Buyeo Goodtrae Gran Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Buyeo') WHERE slug = 'buyeo';
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Bianchi Chuncheon Gran Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Chuncheon') WHERE slug = 'chuncheon';
UPDATE public.events SET comment_en = 'The 2025 results were updated using the spreadsheet published on October 21.' WHERE slug = 'chuncheon' AND comment = '2025년 데이터는 10월21일 공개된 엑셀파일의 내용을 토대로 업데이트하였습니다.' AND NULLIF(BTRIM(comment_en), '') IS NULL;
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Samcheok Gran Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Samcheok') WHERE slug = 'samcheok';
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Muju Gran Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Muju') WHERE slug = 'muju';
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Tour de Jinan Plateau'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Jinan, Jeonbuk') WHERE slug = 'jinan';
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Chuncheon Baehu Pass Hill Climb Medio Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Chuncheon') WHERE slug = 'baehu-pass';
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Okjeong Lake Gran Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Imsil') WHERE slug = 'okjeong';
UPDATE public.events SET comment_en = 'Gran Fondo riders without a KOM2 result and Medio Fondo riders without a KOM1 result are classified as DNF.' WHERE slug = 'okjeong' AND comment = '그란폰도에서 KOM2 기록이 없는 경우와 메디오폰도에서 KOM1 기록이 없는 경우는 DNF로 분류하였습니다.' AND NULLIF(BTRIM(comment_en), '') IS NULL;
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Iksan Mireuksa Temple Site Medio Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Iksan') WHERE slug = 'iksan';
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Daegu Gran Festa Gran Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Daegu') WHERE slug = 'daegu';
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Seomseom Yeosu Gran Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Yeosu') WHERE slug = 'yeosu';
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Tongyeong Gran Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Tongyeong') WHERE slug = 'tongyeong';
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Happy Wonju Cherry Blossom Gran Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Wonju') WHERE slug = 'cherry-blossoms';
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Yeongwol Medio Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Yeongwol') WHERE slug = 'yeongwol';
UPDATE public.events SET comment_en = 'The event scheduled for March 29, 2026 was cancelled on March 5.' WHERE slug = 'yeongwol' AND comment = '2026년 3월 29일 예정이었던 대회는 3월 5일에 취소되었습니다' AND NULLIF(BTRIM(comment_en), '') IS NULL;
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Goseong Dinosaur Country Gran Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Goseong Dinosaur Country') WHERE slug = 'dinosour';
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Gapyeong Jaraseom Gran Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Gapyeong') WHERE slug = 'gapyeong';
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Binggrae Gran Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Gongju') WHERE slug = 'bingre';
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Hongcheon Bike Festival Gran Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Hongcheon, Gangwon') WHERE slug = 'hongcheon-festival';
UPDATE public.events SET name_en = COALESCE(NULLIF(BTRIM(name_en), ''), 'Pulse Energy Gran Fondo'), location_en = COALESCE(NULLIF(BTRIM(location_en), ''), 'Yeongdong') WHERE slug = 'pulse';
UPDATE public.courses SET name_en = 'Gran Fondo' WHERE name = '그란폰도' AND NULLIF(BTRIM(name_en), '') IS NULL;
UPDATE public.courses SET name_en = 'Medio Fondo' WHERE name = '메디오폰도' AND NULLIF(BTRIM(name_en), '') IS NULL;
UPDATE public.courses SET name_en = 'MTB' WHERE name = 'MTB' AND NULLIF(BTRIM(name_en), '') IS NULL;
UPDATE public.courses SET name_en = 'Road Cycling' WHERE name = '사이클' AND NULLIF(BTRIM(name_en), '') IS NULL;
UPDATE public.courses SET name_en = 'Rally' WHERE name = '랠리' AND NULLIF(BTRIM(name_en), '') IS NULL;
UPDATE public.courses SET name_en = 'Challenge A' WHERE name = '챌린지A' AND NULLIF(BTRIM(name_en), '') IS NULL;
UPDATE public.courses SET name_en = 'Challenge B' WHERE name = '챌린지B' AND NULLIF(BTRIM(name_en), '') IS NULL;
UPDATE public.courses SET name_en = 'Challenge A' WHERE name = 'Challenge A' AND NULLIF(BTRIM(name_en), '') IS NULL;
UPDATE public.courses SET name_en = 'Challenge B' WHERE name = 'Challenge B' AND NULLIF(BTRIM(name_en), '') IS NULL;
UPDATE public.courses SET name_en = 'Challenge' WHERE name = '챌린지' AND NULLIF(BTRIM(name_en), '') IS NULL;
UPDATE public.courses SET name_en = 'Rain Fondo' WHERE name = '우중폰도' AND NULLIF(BTRIM(name_en), '') IS NULL;
UPDATE public.courses SET name_en = 'Rain Gran Fondo' WHERE name = '우중 그란폰도' AND NULLIF(BTRIM(name_en), '') IS NULL;
UPDATE public.courses SET name_en = 'Rain Medio Fondo' WHERE name = '우중 메디오폰도' AND NULLIF(BTRIM(name_en), '') IS NULL;
UPDATE public.event_editions SET notice_en = 'The Gran Fondo course was cancelled because heavy rain exceeding 20 mm per hour and strong winds were forecast.' WHERE event_id IN (SELECT id FROM public.events WHERE slug = 'seorak') AND year = 2026 AND notice = '시간당 20mm 이상의 폭우와 강한 바람이 예보되어 그란폰도 코스는 취소되었습니다.' AND NULLIF(BTRIM(notice_en), '') IS NULL;
COMMIT;
